"use server";

import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { MONTHLY_GOAL } from "@/lib/seasons";

/**
 * Заполнить дефолтный план на оставшиеся месяцы 2026 для тех ownerId+month,
 * где он ещё не задан. Идемпотентно: существующие значения не перезаписываем.
 *
 * Дефолт: 10 артикулов и 20 000 шт / месяц, распределённые между активными
 * продакт-менеджерами как можно равнее (10 / N округлённо, остаток первым).
 *
 * Записи создаются с category=null — это «общий план по PM на месяц».
 * Существующие категорийные шаблоны (PMOwner=null + category=…) не трогаем.
 */
export async function fillDefaultPlan2026(): Promise<{
  ok: boolean;
  created: number;
  skipped: number;
  error?: string;
}> {
  const session = await auth();
  const role = (session?.user as { role?: string } | undefined)?.role;
  if (role !== "OWNER" && role !== "DIRECTOR") {
    return { ok: false, created: 0, skipped: 0, error: "Только владелец/директор" };
  }

  // Алёна (OWNER) — руководитель отдела, она НЕ несёт KPI. План распределяется
  // только между PRODUCT_MANAGER. Если PM меньше 1 — нечего делить.
  const pms = await prisma.user.findMany({
    where: {
      isActive: true,
      role: "PRODUCT_MANAGER",
    },
    select: { id: true, name: true, role: true },
    orderBy: { name: "asc" },
  });
  if (pms.length === 0) return { ok: false, created: 0, skipped: 0, error: "Нет активных PRODUCT_MANAGER" };

  const today = new Date();
  const startYm = today.getFullYear() * 100 + (today.getMonth() + 1);
  const months: number[] = [];
  // До конца текущего года.
  for (let ym = startYm; Math.floor(ym / 100) === today.getFullYear(); ym += 1) {
    if (ym % 100 > 12) break;
    months.push(ym);
  }

  // Уже существующие планы на месяцы и PM (только category=null — общие планы).
  const existing = await prisma.monthlyPlan.findMany({
    where: { yearMonth: { in: months }, category: null },
    select: { yearMonth: true, ownerId: true },
  });
  const existKey = new Set(existing.map((e) => `${e.yearMonth}|${e.ownerId ?? ""}`));

  // Раскладка 10 артикулов и 20 000 шт на N PM. Округление: первый получает
  // остаток, остальные — равномерно.
  const N = pms.length;
  const baseModels = Math.floor(MONTHLY_GOAL.models / N);
  const remModels = MONTHLY_GOAL.models - baseModels * N;
  const baseQty = Math.floor(MONTHLY_GOAL.quantity / N);
  const remQty = MONTHLY_GOAL.quantity - baseQty * N;

  let created = 0;
  let skipped = 0;

  for (const ym of months) {
    for (let i = 0; i < N; i++) {
      const pm = pms[i];
      const key = `${ym}|${pm.id}`;
      if (existKey.has(key)) {
        skipped++;
        continue;
      }
      const models = baseModels + (i < remModels ? 1 : 0);
      const qty = baseQty + (i < remQty ? 1 : 0);
      try {
        await prisma.monthlyPlan.create({
          data: {
            yearMonth: ym,
            ownerId: pm.id,
            category: null,
            plannedModelCount: models,
            plannedQuantity: qty,
            notes: "Сгенерирован автоматически (цель 10/20 000 на PM)",
          },
        });
        created++;
      } catch {
        skipped++;
      }
    }
  }

  revalidatePath("/seasons");
  revalidatePath("/plan-vs-fact");
  return { ok: true, created, skipped };
}

/**
 * Удалить все автосгенерированные планы (по метке в notes) за ТЕКУЩИЙ год.
 * Год берём динамически (не хардкод 2026), чтобы кнопка не устарела с января.
 * Безопасно: не трогает планы введённые вручную (там notes другой/null).
 */
export async function clearAutoGeneratedPlan2026(): Promise<{ ok: boolean; deleted: number; error?: string }> {
  const session = await auth();
  const role = (session?.user as { role?: string } | undefined)?.role;
  if (role !== "OWNER" && role !== "DIRECTOR") {
    return { ok: false, deleted: 0, error: "Только владелец/директор" };
  }
  const year = new Date().getFullYear();
  const r = await prisma.monthlyPlan.deleteMany({
    where: {
      yearMonth: { gte: year * 100 + 1, lte: year * 100 + 12 },
      notes: "Сгенерирован автоматически (цель 10/20 000 на PM)",
    },
  });
  revalidatePath("/seasons");
  revalidatePath("/plan-vs-fact");
  return { ok: true, deleted: r.count };
}
