"use client";

import { useState, useTransition } from "react";
import { fillDefaultPlan2026, clearAutoGeneratedPlan2026 } from "./actions";

/**
 * Кнопки «Заполнить дефолтный план» и «Очистить автосгенерированное».
 * Алёна (или директор) тыкает один раз — все пустые слоты MonthlyPlan на
 * оставшиеся месяцы 2026 заполняются цифрами 10/20 000, равномерно на
 * активных PRODUCT_MANAGER. Существующие значения не трогаются.
 *
 * Очистка — только записи с notes='Сгенерирован автоматически …'; вручную
 * введённые планы не удаляются.
 */
export function FillPlanButton() {
  const [pending, startTransition] = useTransition();
  const [result, setResult] = useState<string | null>(null);

  function onFill() {
    if (pending) return;
    if (!window.confirm("Заполнить пустые слоты плана на оставшиеся месяцы 2026 цифрами 10 артикулов и 20 000 шт на месяц, поровну между активными PRODUCT_MANAGER?")) return;
    startTransition(async () => {
      const r = await fillDefaultPlan2026();
      setResult(!r.ok ? (r.error ?? "Не получилось") : `Создано ${r.created}, пропущено (уже было) ${r.skipped}`);
    });
  }

  function onClear() {
    if (pending) return;
    if (!window.confirm("Удалить ВСЕ автосгенерированные планы 2026? Введённые вручную планы не пострадают.")) return;
    startTransition(async () => {
      const r = await clearAutoGeneratedPlan2026();
      setResult(!r.ok ? (r.error ?? "Не получилось") : `Удалено ${r.deleted}`);
    });
  }

  return (
    <div className="flex flex-wrap items-center gap-2">
      <button
        type="button"
        onClick={onFill}
        disabled={pending}
        className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-50 disabled:opacity-50"
      >
        {pending ? "…" : "✦ Заполнить дефолтный план"}
      </button>
      <button
        type="button"
        onClick={onClear}
        disabled={pending}
        className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-sm text-slate-500 hover:border-red-300 hover:text-red-600 disabled:opacity-50"
        title="Удалить только автосгенерированные (notes = …)"
      >
        Очистить
      </button>
      {result && <span className="text-xs text-slate-500">{result}</span>}
    </div>
  );
}
